100.get-started=Get started
  10.overview=Overview
  50.embedded-mode=Embedded mode
  100.client-server-mode=Client/Server mode
  150.build-ai-apps=Build AI applications
200.develop=Develop
  100.vector-search=Vector search
    100.vector-search-overview=Vector search overview
    200.vector-index=Vector index
      400.sparse-vector-index=Sparse vector index
    700.vector-search-reference=Reference guide
      900.vector-search-supported-clients-and-languages=Supported clients and languages
  200.hybrid-search=Hybrid search
  300.ai-function=AI functions
  400.mcp-server=MCP Server
  500.multi-model=Multi-model data
    100.json=JSON data
    200.spatial=Spatial data
    300.char-and-text=Character and text data
300.integrations=Integrations
  100.frameworks=Frameworks
  200.model-platforms=Model platforms
  300.developer-tools=Developer tools
  400.workflows=Workflows
  500.data-ingestion=Data ingestion
  600.mcp=MCP
400.guides=Guides
  400.deploy=Deploy seekdb
    500.environment-and-configuration-checks=Pre-deployment preparation
    700.server-mode=Server mode
  500.manage=Manage
    100.configuration-management=Configuration management
      200.system-configuration-items=Configuration items
      300.system-variable=System variables
    200.high-availability=High availability
    	200.recyclebin=Recyclebin
    300.security=Security and permissions
      200.identification-and-authentication=Identification and authentication
      300.access-control=Access control
        200.user-and-permission=User and permissions
          340.role-management=Role management
      400.data-transfer-encryption=Data transmission encrption   
  1000.obshell=obshell
    300.obshell-clients=obshell commands
    350.obshell-dashboard=obshell Dashboard
  1100.performance-test=Performance test
    100.vectordbbench-test-on-seekdb=Vectordbbench
    200.sysbench-test-on-seekdb=Sysbench
  1300.release-notes=Release notes
450.reference=Reference
  200.sql=SQL reference
    100.sql-syntax=SQL syntax
      100.basic-elements=Basic elements
        100.data-type=Data types
          200.numeric=Numeric types
          300.date-and-time-types=Datetime types
          400.string=String types
          500.large-object=Large objects and text types
          800.json-formatted-data-type=JSON data types
          900.spatial-data-type=Spatial data types
          1000.roaring-bitmap-data-type=Roaring bitmap types
          1200.array-data-type=Array data types
          1300.map-data-type=Map data types
        200.expression=Expressions
        300.character-set-and-collation=Character set and collation
        400.literal=Literals
      200.operator=Operators
    300.pl=PL reference
      100.what-is-pl=What is PL
      200.storage-object=PL stored procedures
      300.cursor=PL cursors
      400.control-statement=PL conditional control statements
      500.pl-manipulation-statement-mysql=PL data manipulation statements
      600.sql-statements-for-pl-stored-programs=PL data definition statements
      700.pl-database-management-statements=PL database management statements
      800.information-schema-dictionary-view=PL related dictionary views
      900.pl-exception-handling-statement=PL exception handling
  600.error-code=Error Code
  900.sdk=SDK
    10.pyseekdb-sdk=pyseekdb
      50.sdk-samples=SDK samples
    50.apis=APIs
      110.database=Database
      200.collection=Collection
      300.dml=DML
      400.dql=DQL
    60.embedding-funcations=User-defined functions
500.tutorials=Tutorials
  100.create-ai-app-demo=Build AI applications
600.demos=Demos