100.get-started=Get started
  10.overview=seekdb 概述
  50.embedded-mode=嵌入式模式
  100.client-server-mode=服务器模式
  150.build-ai-apps=搭建 AI 应用
200.develop=Develop
  100.vector-search=向量搜索
    100.vector-search-overview=向量搜索概述
    200.vector-index=向量索引
      400.sparse-vector-index=稀疏向量索引
    700.vector-search-reference=参考指南
      900.vector-search-supported-clients-and-languages=支持的客户端和语言
  200.hybrid-search=混合搜索
  300.ai-function=AI 函数服务
  400.mcp-server=MCP Server
  500.multi-model=多模数据
    100.json=JSON 数据
    200.spatial=空间数据
    300.char-and-text=字符和文本数据
  900.sdk=SDK
    10.pyseekdb-sdk=pyseekdb
      50.sdk-samples=SDK 示例
    50.apis=APIs
      110.database=Database
      200.collection=Collection
      300.dml=DML
      400.dql=DQL
    60.embedding-funcations=自定义函数
  1000.python=Python
300.integrations=Integrations
  100.frameworks=框架
  200.model-platforms=模型平台
  300.developer-tools=编程工具
  400.workflows=工作流
  500.data-ingestion=数据采集
  600.mcp=MCP
400.guides=Guides
  400.deploy=部署 SeekDB
    500.environment-and-configuration-checks=部署前准备
    700.server-mode=服务器模式
  500.manage=管理 seekdb
    100.configuration-management=配置管理
      200.system-configuration-items=配置项
      300.system-variable=系统变量
    200.high-availability=高可用
    	200.recyclebin=回收站管理
  1000.obshell=运维工具 obshell
    300.obshell-clients=obshell 命令
    350.obshell-dashboard=obshell Dashboard
  1100.performance-test=性能测试
    100.vectordbbench-test-on-seekdb=seekdb Vectordbbench 测试
    200.sysbench-test-on-seekdb=seekdb Sysbench 测试
  1200.reference=参考
  1300.release-notes=Release notes
500.tutorials=Tutorials
  100.create-ai-app-demo=搭建 AI 应用
600.demos=Demos