100.get-started=Get started
  50.quick-start=Quick start
    100.create-ai-app-demo=Build AI applications
200.develop=Develop
  100.vector-search=Vector search
    100.vector-search-overview=Vector search overview
    200.vector-index=Vector index
      400.sparse-vector-index=Sparse vector index
    700.vector-search-reference=Reference guide
      900.vector-search-supported-clients-and-languages=Supported clients and languages
  200.hybrid-search=Hybrid search
  300.ai-function=AI functions
  500.multi-model=Multi-model data
    100.json=JSON data
    200.spatial=Spatial data
    300.char-and-text=Character and text data
300.integrations=Integrations
    100.model=Models
    200.frame=Frameworks
    300.mcp-client=MCP clients
400.guides=Guides
  400.deploy=Deploy SeekDB
    500.environment-and-configuration-checks=Pre-deployment preparation
    700.server-mode=Server mode 
  1000.obshell=obshell
    300.obshell-clients=obshell commands
    350.obshell-dashboard=obshell Dashboard
700.release-notes=Release notes