100.get-started=Get started
  10.overview=Overview
  50.embedded-mode=Embedded mode
  100.client-server-mode=Client/Server mode
  150.build-ai-apps=Build AI applications
200.develop=Develop
  100.vector-search=Vector search
    100.vector-search-overview=Vector search overview
    200.vector-index=Vector index
      400.sparse-vector-index=Sparse vector index
    700.vector-search-reference=Reference guide
      900.vector-search-supported-clients-and-languages=Supported clients and languages
  200.hybrid-search=Hybrid search
  300.ai-function=AI functions
  400.mcp-server=MCP Server
  500.multi-model=Multi-model data
    100.json=JSON data
    200.spatial=Spatial data
    300.char-and-text=Character and text data
  900.sdk=SDK
    10.pyseekdb-sdk=pyseekdb
      50.sdk-samples=SDK samples
    50.apis=APIs
      110.database=Database
      200.collection=Collection
      300.dml=DML
      400.dql=DQL
    60.embedding-funcations=User-defined functions
  1000.python=Python
300.integrations=Integrations
  100.frameworks=Frameworks
  200.model-platforms=Model Platforms
  300.developer-tools=Developer Tools
  400.workflows=Workflows
  500.data-ingestion=Data Ingestion
  600.mcp=MCP
400.guides=Guides
  400.deploy=Deploy seekdb
    500.environment-and-configuration-checks=Pre-deployment preparation
    700.server-mode=Server mode 
  1000.obshell=obshell
    300.obshell-clients=obshell commands
    350.obshell-dashboard=obshell Dashboard
  1200.reference=Reference
  1300.release-notes=Release notes
500.tutorials=Tutorials
  100.create-ai-app-demo=Build AI applications
600.demos=Demos