100.get-started=Get started
  10.overview=seekdb 概述
  50.embedded-mode=嵌入式模式
  100.client-server-mode=服务器模式
  150.build-ai-apps=搭建 AI 应用
200.develop=Develop
  100.vector-search=向量搜索
    100.vector-search-overview=向量搜索概述
    200.vector-index=向量索引
      400.sparse-vector-index=稀疏向量索引
    700.vector-search-reference=参考指南
      900.vector-search-supported-clients-and-languages=支持的客户端和语言
  200.hybrid-search=混合搜索
  300.ai-function=AI 函数服务
  400.mcp-server=MCP Server
  500.multi-model=多模数据
    100.json=JSON 数据
    200.spatial=空间数据
    300.char-and-text=字符和文本数据
  900.sdk=SDK
    10.pyseekdb-sdk=pyseekdb
      50.sdk-samples=SDK 示例
    50.apis=APIs
      110.database=Database
      200.collection=Collection
      300.dml=DML
      400.dql=DQL
    60.embedding-funcations=自定义函数
  1000.python=Python
300.integrations=Integrations
    100.model=模型
    200.frame=框架
    300.mcp-client=MCP Client
400.guides=Guides
  400.deploy=部署 SeekDB
    500.environment-and-configuration-checks=部署前准备
    700.server-mode=服务器模式 
  1000.obshell=obshell
    300.obshell-clients=obshell 命令
    350.obshell-dashboard=obshell Dashboard
  1200.reference=参考
  1300.release-notes=Release notes
500.tutorials=Tutorials
  100.create-ai-app-demo=搭建 AI 应用
600.demos=Demos